### ISSUE TITLE
Release annotations using API keys will be retired on 31 August 2024

### ISSUE THREAD

**Issue by bradyclifford** [im-open/create-app-insights-annotation#9]
https://azure.microsoft.com/en-us/updates/transition-to-new-release-annotations-in-application-insights/

**Comment by danielle-casella-adams** [comment]
I feel like I might be missing something here.  This action doesn't use an API key.  It relies on the user logging in to azure before this action is called.  The action.yml script was based on Microsoft's [Create release annotations with the Azure CLI](https://learn.microsoft.com/en-us/azure/azure-monitor/app/release-and-work-item-insights?tabs=release-annotations#create-release-annotations-with-the-azure-cli).  If you look at the link above, it has recommendations for transitioning, and those links go to the same site that this script was based on.

What am I missing?

**Comment by bradyclifford** [comment]
I don't remember what this was for as well.
